services:
  - type: web
    name: resume-analyzer-backend
    runtime: docker
    plan: free
    rootDir: .
    healthCheckPath: /health
    envVars:
      - key: 4c79ad07
        sync: false
      - key: 59cf3dcddd5157272f49ed52c00f2ea9
        sync: false
      - key: http://localhost:5173
        sync: false
