spring.application.name=resume-analyzer
server.port=8080
adzuna.base-url=https://api.adzuna.com/v1/api
adzuna.country=in
adzuna.results-per-page=10
adzuna.app-id=${ADZUNA_APP_ID}
adzuna.app-key=${ADZUNA_APP_KEY}
